# Generated by Django 6.0 on 2025-12-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, unique=True, verbose_name='Título del Libro')),
                ('cod', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('author', models.ManyToManyField(to='HolaMundo.author')),
            ],
        ),
    ]
