# Generated by Django 6.0 on 2025-12-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HolaMundo', '0002_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
